@startuml Context Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FONTAWESOME/users.puml

Person(users, "Users", "Regular users, traders, investors", $sprite="users")
Person(regulator, "Regulator", "Check for suspicious transactions")
Person(admin, "Admin", "Monitor operations")

Container(currency_app, "Currency App", "Handles users' data, stock rates and transactions business logic")

Rel(users, currency_app, "Exchange currencies, monitor changes", "https")
Rel(regulator, currency_app, "Get reports, approve or decline suspicious transactions", "https")
Rel(admin, currency_app, "Update stock rates, monitor operations", "https")
@enduml
