@startuml State Diagram
state "Транзакции" as Transaction
state "Подтвреждение" as Approval
state "Регулятор" as Regulator
state "Отказ" as Failure
state "Завершен" as Finished

[*] --> NewRequest
NewRequest --> Transaction : Клиент создал транзакцию
Transaction --> Approval : Транзакция моментально подтверждена
Transaction --> Regulator : Транзакция требует внимания регулятора
Approval --> Finished
Regulator --> Failure : Нежелательная транзакция
Regulator --> Finished : Транзакция успешно проведена
Finished --> [*]
@enduml
