@startuml Infrastructure Diagram
[Mobile App]
package "Currency App" {
    package "api-gateway" {
        [Frontend server]
        [API Gateway]
    }
    package "regulator" {
        [Api]
        [App]
        [Infrastructure]
        [Domain]
        [Database]
    }
    package "rates" {
        [Rates]
    }
    package "user" {
        [User]
    }
    package "wallet" {
        [Wallet]
    }
    package "transaction" {
        [Transaction]
    }
    package "registry" {
        [docker-registry]
        [docker-registry-auth-proxy]
    }
    package "rancher" {
        [Rancher]
    }
    [Ingress Controller]
    [Kubeapi]
}

[docker-registry-auth-proxy] --> [docker-registry]

[Api] --> [App]
[App] --> [Infrastructure]
[App] --> [Domain]
[Infrastructure] --> [Domain]
[Infrastructure] --> [Database]

[Ingress Controller] --> [docker-registry-auth-proxy]
[Ingress Controller] --> [api-gateway]
[Ingress Controller] --> [Frontend server]

[api-gateway] --> [API Gateway]
[API Gateway] --> [regulator]
[API Gateway] --> [rates]
[API Gateway] --> [user]
[API Gateway] --> [wallet]
[API Gateway] --> [transaction]


actor Client
[Client] --> [Ingress Controller]

actor Developer
[Developer] --> [Rancher]
[Developer] --> [Ingress Controller]
[Rancher] --> [Kubeapi]
@enduml