@startuml Infrastructure Diagram
[Mobile App]
package "k3s cluster" {
    package "Currency App" {
        [Database]
        [API Gateway]
        [Monolith]
    }
    package "registry" {
        [docker-registry]
        [docker-registry-auth-proxy]
    }
    package "s3-storage" {
        [S3 storage] as Minio
    }
    package "rancher" {
        [Rancher]
    }
    [Ingress Controller]
    [Kubeapi]
}

[docker-registry-auth-proxy] --> [docker-registry]

[Ingress Controller] --> [docker-registry-auth-proxy]
[Ingress Controller] --> [Minio]
[Ingress Controller] --> [API Gateway]

[API Gateway] --> [Monolith]

[Monolith] --> [Database]


actor User
[User] --> [Mobile App]
[Mobile App] --> [Ingress Controller]

actor Developer
[Developer] --> [Rancher]
[Developer] --> [Ingress Controller]
[Rancher] --> [Kubeapi]
@enduml
